;;; -*- Mode: LISP; Syntax: COMMON-LISP; Package: PREPARE-FM-PLUGIN-TOOLS; Base: 10 -*-

;;; Copyright (c) 2022, Chun Tian (binghe).  All rights reserved.

;;; Redistribution and use in source and binary forms, with or without
;;; modification, are permitted provided that the following conditions
;;; are met:

;;;   * Redistributions of source code must retain the above copyright
;;;     notice, this list of conditions and the following disclaimer.

;;;   * Redistributions in binary form must reproduce the above
;;;     copyright notice, this list of conditions and the following
;;;     disclaimer in the documentation and/or other materials
;;;     provided with the distribution.

;;; THIS SOFTWARE IS PROVIDED BY THE AUTHOR 'AS IS' AND ANY EXPRESSED
;;; OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
;;; WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;;; ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
;;; DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
;;; DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
;;; GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;;; INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
;;; WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
;;; NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
;;; SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

(in-package :prepare-pdf-plugin-tools)

(defparameter *header-file-names*
  '("CorProcs" ; Catalog of the "core" exported functions; this table is handed off to the plug-in at initialization time,
    ; "ASProcs"  ; Catalog of functions exported by AcroSupport
    )
  "The list of involved Acrobat SDK header files in the right order, so
that we process the needed typedes etc. first.")

(defvar *sdk-extern-location* nil
  "A pathname designator denoting where exactly Acrobat Pro SDK's
PluginSupport/Headers/API directory can be found.  You either set it here, or you'll get
a dialog asking for it.")

(defparameter *fli-file* (merge-pathnames "../fli.lisp"
                                          (load-time-value
                                            (or #.*compile-file-pathname* *load-pathname*)))
  "The target file \(to become a part of the PDF-PLUGIN-TOOLS
system) which is generated by this library.")

(defvar *function-counter* 0
  "This variable records the offset of each API functions in the corresponding HFT,
during the processing of each XXXProcs.h header file.")

