;;; This file was generated automatically from Acrobat Pro's SDK headers.

(in-package :pdf-plugin-tools) 

;; #include <ASNumTypes.h>
(define-c-typedef as-int8 (:signed :byte))
(define-c-typedef as-int8p (:pointer as-int8))
(define-c-typedef as-int16 (:short :int))
(define-c-typedef as-int16p (:pointer as-int16))
(define-c-typedef as-int32 :int)
(define-c-typedef as-int32p (:pointer as-int32))
(define-c-typedef as-int64 (:signed :long :long :int))
(defconstant +as-max-int8+ #x7F)
(defconstant +as-min-int8+ #x80)
(defconstant +as-max-int16+ #x7FFF)
(defconstant +as-min-int16+ #x8000)
(defconstant +as-max-int32+ #x7FFFFFFF)
(defconstant +as-min-int32+ #x80000000)
(defconstant +as-max-int64+ #x7FFFFFFFFFFFFFFF)
(defconstant +as-min-int64+ #x8000000000000000)
(define-c-typedef as-uns8 (:unsigned :byte))
(define-c-typedef as-uns8p (:pointer as-uns8))
(define-c-typedef as-uns16 (:unsigned :short :int))
(define-c-typedef as-uns16p (:pointer as-uns16))
(define-c-typedef as-uns32 (:unsigned :int))
(define-c-typedef as-uns32p (:pointer as-uns32))
(define-c-typedef as-uns64 (:unsigned :long :long :int))
(define-c-typedef as-int-or-ptr :intptr)
(define-c-typedef as-uns-or-ptr :uintptr)
(defconstant +as-max-uns8+ #xFF)
(defconstant +as-min-uns8+ #x0)
(defconstant +as-max-uns16+ #xFFFF)
(defconstant +as-min-uns16+ #x0)
(defconstant +as-max-uns32+ #xFFFFFFFF)
(defconstant +as-min-uns32+ #x0)
(defconstant +as-max-uns64+ #xFFFFFFFFFFFFFFFF)
(defconstant +as-min-uns64+ #x0)
(define-c-typedef as-bool as-uns16)
(define-c-typedef as-size-t :size-t)
(define-c-typedef as-int-ptr-t :intptr)

;; #include <CoreExpT.h>