;;; This file was generated automatically from Acrobat Pro's SDK headers.

(in-package :pdf-plugin-tools) 

;; #include <ASNumTypes.h>
(define-c-typedef as-int8 (:signed :byte))
(define-c-typedef as-int8p (:pointer as-int8))
(define-c-typedef as-int16 (:short :int))
(define-c-typedef as-int16p (:pointer as-int16))
(define-c-typedef as-int32 :int)
(define-c-typedef as-int32p (:pointer as-int32))
(define-c-typedef as-int64 (:signed :long :long :int))
(defconstant +as-max-int8+ #x7F)
(defconstant +as-min-int8+ #x80)
(defconstant +as-max-int16+ #x7FFF)
(defconstant +as-min-int16+ #x8000)
(defconstant +as-max-int32+ #x7FFFFFFF)
(defconstant +as-min-int32+ #x80000000)
(defconstant +as-max-int64+ #x7FFFFFFFFFFFFFFF)
(defconstant +as-min-int64+ #x8000000000000000)
(define-c-typedef as-uns8 (:unsigned :byte))
(define-c-typedef as-uns8p (:pointer as-uns8))
(define-c-typedef as-uns16 (:unsigned :short :int))
(define-c-typedef as-uns16p (:pointer as-uns16))
(define-c-typedef as-uns32 (:unsigned :int))
(define-c-typedef as-uns32p (:pointer as-uns32))
(define-c-typedef as-uns64 (:unsigned :long :long :int))
(define-c-typedef as-int-or-ptr :intptr)
(define-c-typedef as-uns-or-ptr :uintptr)
(defconstant +as-max-uns8+ #xFF)
(defconstant +as-min-uns8+ #x0)
(defconstant +as-max-uns16+ #xFFFF)
(defconstant +as-min-uns16+ #x0)
(defconstant +as-max-uns32+ #xFFFFFFFF)
(defconstant +as-min-uns32+ #x0)
(defconstant +as-max-uns64+ #xFFFFFFFFFFFFFFFF)
(defconstant +as-min-uns64+ #x0)
(define-c-typedef as-bool (:boolean as-uns16))
(define-c-typedef as-size :size-t)
(define-c-typedef as-int-ptr :intptr)

;; #include <CoreExpT.h>
(define-c-typedef as-enum8 as-int8)
(define-c-typedef as-enum16 as-int16)
(define-c-typedef k-as-max-enum8 as-max-int8)
(define-c-typedef k-as-max-enum16 as-max-int16)
(define-c-typedef opaque-32-bits as-int32)
(define-c-typedef as-atom as-uns16)
(define-c-typedef as-atom-null as-max-uns16)
(define-c-typedef selector as-int32)
(define-c-typedef hft-entry (:pointer :void))
(define-c-typedef hft (:pointer hft-entry))
(define-opaque-pointer -t-as-extension nil)
(define-c-typedef extension-id as-extension)
(define-c-typedef as-callback (:pointer :void))
(define-c-struct opaque-64-bits (a opaque-32-bits) (b opaque-32-bits))

;; #include <ASExpT.h>
(define-c-typedef as-file-mode as-uns16)
(define-c-typedef as-file-pos as-uns32)
(define-c-typedef as-file-offset as-int32)
(define-c-typedef as-file-offset64 as-int64)
(define-c-typedef as-file-pos64 as-uns64)
(define-c-typedef as-error-code as-int32)
(define-c-typedef as-byte-count as-uns32)
(define-c-typedef as-array-size as-uns32)
(define-c-typedef as-flag-bits as-uns32)
(define-c-typedef as-disk-space as-uns32)
(define-c-typedef as-disk-space64 as-uns64)
(define-c-typedef a-sl-file-mode as-uns32)
(define-c-typedef as-mask-bits as-uns32)
(define-c-typedef as-duration as-int32)
(define-c-typedef as-version as-uns32)
(define-c-typedef as-small-buffer-size as-uns16)
(define-c-typedef as-count as-uns32)
(define-c-typedef as-byte as-uns8)
(define-c-typedef as-small-count as-int16)
(define-c-typedef ast-file-pos as-int32)
(define-c-typedef ast-array-size as-int32)
(define-c-typedef ast-version as-int32)
(define-c-typedef ast-count as-int32)
(define-c-typedef as-coord as-int16)
(define-c-typedef as-err-severity as-enum8)
(define-c-typedef as-stm-rec (struct -t-as-stm-rec))
(define-c-typedef as-stm (:pointer as-stm-rec))
(define-opaque-pointer -t-as-crypt-stm-rec nil)
(define-opaque-pointer -t-hft-server nil)
(define-c-typedef as-fixed as-int32)
(define-c-typedef as-fixed-p (:pointer as-fixed))
(define-c-typedef as-fixed-pos-inf as-max-int32)
(define-c-typedef as-fixed-neg-inf as-min-int32)
(define-c-typedef int32to-fixed as-int32to-fixed)
(define-c-typedef fixed-round-to-int32 as-fixed-round-to-int32)
(define-c-typedef fixed-trunc-to-int32 as-fixed-trunc-to-int32)
(define-c-typedef int16to-fixed as-int16to-fixed)
(define-c-typedef fixed-round-to-int16 as-fixed-round-to-int16)
(define-c-typedef fixed-trunc-to-int16 as-fixed-trunc-to-int16)
(define-c-typedef fixed-negative-infinity as-fixed-neg-inf)
(define-c-typedef fixed-positive-infinity as-fixed-pos-inf)
(define-c-typedef as-fract as-int32)
(define-c-typedef as-real float)
(define-c-typedef as-double double)
(define-c-typedef as-double-p (:pointer as-double))
(define-opaque-pointer -t-as-cabinet nil)
(define-opaque-pointer -t-as-cabinet const\ )
(define-opaque-pointer -t-as-text-rec nil)
(define-opaque-pointer -t-as-text-rec const\ )
(define-c-typedef k-acrobat-creator-code as-four-char-code)
(define-c-typedef k-photoshop-creator-code as-four-char-code)
(define-c-typedef k-image-ready-creator-code as-four-char-code)
(define-c-typedef k-illustrator-creator-code as-four-char-code)
(define-c-typedef k-pdf-type-code as-four-char-code)
(define-c-typedef k-fdf-type-code as-four-char-code)
(define-c-typedef k-xfdf-type-code as-four-char-code)
(define-c-typedef k-xdp-type-code as-four-char-code)
(define-c-typedef k-pxdf-type-code as-four-char-code)
(define-c-typedef k-prefs-type-code as-four-char-code)
(define-c-typedef k-pdx-type-code as-four-char-code)
(define-c-typedef k-rmf-type-code as-four-char-code)
(define-c-typedef k-apf-type-code as-four-char-code)
(define-c-typedef k-sequence-type-code as-four-char-code)
(define-c-typedef k-dictionary-type-code as-four-char-code)
(define-c-typedef k-wha-type-code as-four-char-code)
(define-c-typedef k-locale-type-code as-four-char-code)
(define-c-typedef k-plugin-type-code as-four-char-code)
(define-c-typedef k-plugin-new-type-code as-four-char-code)
(define-c-typedef k-etd-type-code as-four-char-code)
(define-c-typedef k-edn-type-code as-four-char-code)
(define-c-typedef k-psd-type-code as-four-char-code)
(define-c-typedef k-pict-type-code as-four-char-code)
(define-c-typedef k-tiff-type-code as-four-char-code)
(define-c-typedef k-gif-type-code as-four-char-code)
(define-c-typedef k-jpeg-type-code as-four-char-code)
(define-c-typedef k-png-type-code as-four-char-code)
(define-c-typedef kai-type-code as-four-char-code)
(define-c-typedef k-eps-type-code as-four-char-code)
(define-c-typedef k-text-type-code as-four-char-code)
(define-c-typedef k-rtf-type-code as-four-char-code)
(define-c-typedef k-text-creator-code as-four-char-code)
(define-c-typedef k-quick-time-type-code as-four-char-code)
(define-c-typedef k-quick-time-creator-code as-four-char-code)
(define-c-typedef k-html-type-code as-four-char-code)
(define-c-typedef k-html-creator-code as-four-char-code)
(define-c-typedef k-xml-type-code as-four-char-code)
(define-c-typedef k-excel-creator-code as-four-char-code)
(define-c-typedef k-word-creator-code as-four-char-code)
(define-c-typedef k-power-point-creator-code as-four-char-code)
(define-opaque-pointer -t-as-file-sys-rec nil)
(define-opaque-pointer -t-as-path-name-rec nil)
(define-c-typedef asmd-file (:pointer :void))
(define-c-typedef md-file asmd-file)
(define-opaque-pointer -t-asio-request-rec nil)
(define-c-typedef as-file-sys-item-type as-enum16)
(define-opaque-pointer -t-as-folder-iterator nil)
(define-opaque-pointer -t-as-platform-path nil)
(define-c-typedef cstring-ptr char*)
(define-c-typedef posix-path-ptr char*)
(define-opaque-pointer fs-spec nil)
(define-opaque-pointer fs-ref nil)
(define-c-typedef fs-ref-with-cf-string-ref-rec-ptr
                  (:pointer fs-ref-with-cf-string-ref-rec))
(define-c-typedef cfurl-ref-rec-ptr (:pointer cfurl-ref-rec))
(define-c-typedef progress-monitor as-progress-monitor)
(define-c-typedef progress-monitor-rec as-progress-monitor-rec)
(define-c-typedef cancel-proc as-cancel-proc)
(define-c-typedef as-unicode-format as-enum16)
(define-c-typedef as-host-encoding as-int32)
(define-c-typedef as-unicode-char as-uns32)
(define-c-typedef asutf32val as-uns32)
(define-c-typedef asutf16val as-uns16)
(define-c-typedef asutf8val as-uns8)
(define-c-typedef as-script as-int32)
(define-c-typedef as-date-time-format as-enum8)
(define-opaque-pointer -t-as-date-rec nil)
(define-opaque-pointer -t-as-time-span-rec nil)
